### ISSUE TITLE
Can't get requests to show up made by Deno `fetch`

### ISSUE THREAD

**Issue by Swimburger** [ProxymanApp/Proxyman#2043]
## Description
Can't get requests to show up made by Deno `fetch`

## Steps to Reproduce

1. I use automatic setup
2. Run my Deno script to make a fetch request

## Current Behavior

No requests show up in Proxyman, error:
```
error: Uncaught (in promise) TypeError: error sending request for url (...): error trying to connect: invalid peer certificate: UnknownIssuer
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
```

## Expected Behavior

Requests to show up in Proxyman

## Environment

- App version: 5.4.0 (50400)
- macOS version: ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

**Comment by NghiaTranUIT** [comment]
@Swimburger by default, NodeJS Fetch doesn't follow the system proxy, all traffic goes straight to the Internet.

You can use the Automatic setup feature: https://docs.proxyman.io/automatic-setup/automatic-setup

1. It will open the pre-configured Terminal 
2. Run your NodeJS on this Terminal -> Proxyman automatically captures all fetch, axios, nodejs traffic 👍

**Comment by Swimburger** [comment]
I did use automatic setup. I'm using Deno, not NodeJS.
