### ISSUE TITLE
Node.js Requests don't display in Proxyman

### ISSUE THREAD

**Issue by fishcharlie** [ProxymanApp/Proxyman#236]
### Proxyman version? (Ex. Proxyman 1.4.3)

Proxyman 1.4.7

### macOS Version? (Ex. mac 10.14)

macOS 10.15 Beta (19A526h)

### Steps to reproduce 

1. Open Proxyman
2. Create request in Node.js (ex. https://github.com/axios/axios)
3. Run Node.js script
4. Observe that request doesn't display in Proxyman

### Expected behavior

Request from Node.js to display in Proxyman

### Screenshots (optional)

NA

**Comment by NghiaTranUIT** [comment]
Hey, thank for the report. I will check it out today 👍

**Comment by NghiaTranUIT** [comment]
Hey @fishcharlie, I've checked and the answer is that we have to **explicitly** point the `axios` to Proxyman.

```js
const axios = require('axios');

// Proxy to Proxyman
axios.defaults.proxy = {
    host: '127.0.0.1',
    port: 9090,
}

// Make a request for a user with a given ID
axios.get('https://httpbin.org/get?data=123&value=nghia')
  .then(function (response) {
    // handle success
    console.log(response.data);
  })
  .catch(function (error) {
    // handle error
    console.log(error);
  })
  .finally(function () {
    // always executed
  });
```
then, the request will appear in Proxyman

<img width="1339" alt="Screen_Shot_2019-08-05_at_09_13_40" src="https://user-images.githubusercontent.com/5878421/62434189-cff28900-b761-11e9-962e-3fb09c25c9b3.png">

It's relevant to https://github.com/ProxymanApp/Proxyman/issues/175#issuecomment-515282923, since some CLI doesn't use System Proxy until we explicitly override it.

Additionally, we have to do same for Charles Proxy too.

Hope that could help you 😄 🌮

**Comment by NghiaTranUIT** [comment]
If you don't want to explicitly point the axios to Proxyman, we can use
```
$ export http_proxy=http://127.0.01:9090
$ export https_proxy=http://127.0.01:9090
```
Then all CLIs (curl, nodejs, ...) will automatically proxy to Proxyman, but make sure we remove it when we don't use Proxyman. Or the app will be failed 😄

**Comment by shirshak55** [comment]
actually its working on mine. If we use terminal it wont work directly we need to explicitly say axios to use proxy and that is how it work in other cli apps too :) Every cli supports proxy like curl etc..  And as u have already given implicit way using environment variable its fine.

But please add it in request so other don't get same problem.

**Comment by alnorris** [comment]
I'm getting this when ever I try both the environmental vars and the axios proxy. Any ideas? 
```
Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
```

**Comment by shirshak55** [comment]
@alnorris it can be your server.

**Comment by NghiaTranUIT** [comment]
@alnorris it might be your port is different than the listening port of Proxyman ( default is 9090)

You can go to proxyman Preference and see the port, then setting it correctly

**Comment by NghiaTranUIT** [comment]
If you don’t mind, pls do the same config with other proxy tools to see where the bug is 😄 because there are many hidden factors could affect

**Comment by dvcrn** [comment]
Is there a workaround to enable the proxy for everything? I sometimes have no influence on what the node app is doing, so having an option to transparently proxy everything would be nice. 

Right now I am falling back to mitmproxy which has a workaround using `pfctl` and transparent mode to route traffic system-wide to the proxy. Works pretty good, but if Proxyman could do that out of the box, it would be reaaaally nice

**Comment by shirshak55** [comment]
@dvcrn it still wont work if they enable certs pinning (Like zoom app enable cert pinning). And transparent proxy is different thing than http/https proxy. And regarding node app you will have source code right so you can change proxy easily from source code?

**Comment by NghiaTranUIT** [comment]
I haven't tested `pfctl`, but wondering what happens if we use 9090 in the following script

```
rdr pass on en0 inet proto tcp to any port {80, 443} -> 127.0.0.1 port 9090
```

9090 is where Proxyman serves

**Comment by dvcrn** [comment]
I don't always have access to the source. For example I was pentesting one mac app but it just wasn't showing up in proxyman/charles and I had no idea why. It took me a while to figure out that the app was spawning a node worker in the background that does the connection and that's why nothing was showing up, which got me wondering what else is happening that I'm missing with Proxyman. 

Using mitmproxy + pfctl worked fine even for SSL after trusting the certificate globally

**Comment by shirshak55** [comment]
@dvcrn did u use pfctl to forward to proxyman? BSD uses pf firewall which is abit different than iptables unfortunately.

**Comment by NghiaTranUIT** [comment]
He forwarded it to mitmproxy @shirshak55. Btw, it's a cool idea to use pfctl to do transparent Proxy. 

From what I see, if pfctl can work with Proxyman, we can fix the VPN issue 😄

**Comment by shirshak55** [comment]
@NghiaTranUIT pfctl is just a firewall :) And you should have transparent proxy support on proxyman (I think at the moment proxyman support only Http/Https proxy only). pfctl isn't any magic its like iptables for osx.  Buy the way if you land transparant proxy soon let me know I can help you with docs regarding how to connect andriod with that transparent proxy.

**Comment by NghiaTranUIT** [comment]
There is a workaround by using [proxychains](https://github.com/haad/proxychains) to swamp your app under proxychain umbrella , and all traffic will appear on Proxyman. Read more at https://github.com/ProxymanApp/Proxyman/issues/544

It's quite difficult to set up and requires to disable SIP on your mac, so I would not recommend this approach.

**Comment by shirshak55** [comment]
@dvcrn  I don't know why you are saying charles proxy doesn't work. Charles proxy has transparent proxy so it should have covered your usecase. Its hidden in ssl settings second tab. I haven't used it for year probably but charles proxy does support transparent proxy.

**Comment by Cykelero** [comment]
Seems like Node.js doesn't respect the `http_proxy`/`https_proxy` variables; instead, you need to use something like [global-agent](https://github.com/gajus/global-agent). This is what ended up working in my case.

Step by step:
1. Install global agent: `npm install global-agent`
2. Import it in your code: `require("global-agent/bootstrap")` (or see their docs for how to inject it from the CLI)
3. Set its env variable to Proxyman's server: `export GLOBAL_AGENT_HTTP_PROXY=http://127.0.01:9090`

This should be it!

For those interested, there are lengthy issues on the subject of adding support for the standard proxy vars to Node: https://github.com/nodejs/node/issues/8381, https://github.com/nodejs/node/issues/15620

**Comment by NghiaTranUIT** [comment]
Thank you so much for the contribution 🎉 I will add your comment to official Proxyman doc

**Comment by CyberMew** [comment]
Has this been fixed yet such that even javascript requests in browsers or some apps which I don't have code access to will work, and have the network requests show up?

**Comment by NghiaTranUIT** [comment]
@CyberMew it's not a bug, so I can't fix it. It's how NodeJS works.

If you could not access the source code to change the HTTP Proxy, please try to override on your terminal.

```
export http_proxy=127.0.0.1:9090
export HTTP_PROXY=127.0.0.1:9090
export https_proxy=127.0.0.1:9090
export HTTPS_PROXY=127.0.0.1:9090
```

It is not 100% work if your app doesn't respect the env http_proxy

Ref: https://www.serverlab.ca/tutorials/osx/administration-osx/configuring-a-network-proxy-for-osx/

**Comment by djpowers** [comment]
I wanted to check if people have since found a workaround for this. I had tried exporting HTTP(S) proxy variables, and using the global-agent approach, but didn't have any luck. Have people been successful with any other techniques?

Also it looks like the issues referenced above about adding proxy support to Node have been closed, so I'm wondering if people are aware of any other discussions about making that happen.

**Comment by NghiaTranUIT** [comment]
The solution is depended on what network library you're using on NodeJS. Can you share with me what the lib is? I might google to find a solution 👍

**Comment by NghiaTranUIT** [comment]
Google shows that we can pass the HTTPAgent to tell `node-fetch` to use the Proxy, like this code:

```js
const fetch = require('node-fetch');
const HttpsProxyAgent = require('https-proxy-agent');


(async () => {
    const proxyAgent = new HttpsProxyAgent('http://46.250.171.31:8080');
    const response = await fetch('https://httpbin.org/ip?json', { agent: proxyAgent});
    const body = await response.text();
    console.log(body);
})();
```

However, useFetch wraps the `node-fetch` lib, so I'm not sure how to pass the `HttpsProxyAgent`. Maybe you should ask Raycast devs for hints.

**Comment by shirshak55** [comment]
@NghiaTranUIT if its react, shouldn't it be running in Browser? So, setting global proxies from windows etc. should work?

**Comment by NghiaTranUIT** [comment]
@shirshak55 If it's a React, which access from the web browser or using NodeJS to serve a static file (Build from ReactJS). Proxyman can capture it since the web browser would use the system HTTP Proxy. (Localhost would pass the proxy by default, but there is a solution to fix it).

@djpowers case is different, he is making a request from NodeJS. Thus, it doesn't respect the global/system HTTP proxy.

**Comment by sonic1981** [comment]
I also had to run

```
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';
```

**Comment by gkatsanos** [comment]
set the shell env vars, 
```sh
master   pnpm start

> request-frontend@0.0.1 start /Users/gkatsanos/repos/visable/requests-frontend
> NODE_OPTIONS='-r dd-trace/init' HOST=0.0.0.0 PORT=3000 node ./dist/server/entry.mjs

HTTP_PROXY 192.168.1.107:9090
HTTPS_PROXY 192.168.1.107:9090
Server listening on http://0.0.0.0:3000
```

:white_check_mark removed local bypass in OSX configuration
:white_check_mark added the /etc/hosts entries:
```

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
# Added by Docker Desktop

127.0.0.1 www.wlw-local.de
# START wlw-compose-setup
127.0.0.1 local.wlw.de local.wlw.at local.wlw.ch api.local.visable.com
127.0.0.1 redirect.local.wlw.de redirect.local.wlw.at redirect.local.wlw.ch
127.0.0.1 api.local.visable.com
127.0.0.1 aws.local.visable.com
127.0.0.1 www.local.europages.co.uk
# END wlw-compose-setup

```
 tried: http://0.0.0.0:3000/status/health , no logs
http://proxyman.local:3000/ - same, no logs
http://localhost.proxyman.io:3000/requests-frontend/status/health - no logs

Could someone explain why would someone buy this product which is supposed to work out of the box but doesnt work even after 3-4 workarounds/hacks?

**Comment by NghiaTranUIT** [comment]
> Could someone explain why would someone buy this product which is supposed to work out of the box but doesnt work even after 3-4 workarounds/hacks?

Sorry @gkatsanos, the problem is from the NodeJS, it doesn't respect the system HTTP Proxy, so it doesn't work out of the box. If you develop iOS/Android app, it works out of the box.

Your /etc/host looks like doesn't have the following line:
```
127.0.0.1 proxyman.local
::1 proxyman.local
```

Thus, http://proxyman.local:3000/ doesn't work.

Ref: https://docs.proxyman.io/troubleshooting/couldnt-see-any-request-from-localhost-server#solution-2-map-localhost-to-the-domain-name-in-etc-hosts

**Comment by gkatsanos** [comment]
But then why recommend to people to set the HTTP_PROXY environment variables in their shell?
I feel everytime I try to use Proxyman I'm ping ponged from hack to hack..

**Comment by NghiaTranUIT** [comment]
It's because NodeJS development is really messy. Some libraries require the HTTP_PROXY env, some don't respect the System Proxy -> Needs to manually config in their source code, and some libs do respect the proxy -> Proxyman can work out of the box.

There is no silver bullet to fix all NodeJS problems **automatically**.

Proxyman helps you a lot behind the scene that you don't notice, such as auto install the certificate on your Mac, auto overriding/reverting the system proxy, or auto-scripts for iOS, and Android, ...

You can try other tools, Charles Proxy, Fiddler, Wireshark, and you have to google a lot to make it works with NodeJS too.

**Comment by NghiaTranUIT** [comment]
@gkatsanos it depends on your setup. If you don't mind, what is the NodeJS web framework you're using?

Here is a simple sample:
1. Use ExpressJS to create a localhost server
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```


2. Open /etc/hosts and add the following text:
```
127.0.0.1 proxyman.local
::1 proxyman.local
```

3. Done. Use Google Chrome, visit `http://proxyman.local:3000` -> Proxyman will capture the traffic as usual.

![CleanShot 2023-04-15 at 10 18 40@2x](https://user-images.githubusercontent.com/5878421/232180487-985733a0-516f-4e85-9bf6-b3e8b1903ecb.jpg)

**Comment by NghiaTranUIT** [comment]
@gkatsanos I've updated the NodeJS Documentation to make it clears what the Proxyman & solution: https://docs.proxyman.io/debug-devices/nodejs

**Comment by gkatsanos** [comment]
I use Astro which comes with a pre-bundled NodeJS server. I cant really modify the respond/request code on the node side so I would ideally do this outside the node application if possible..

**Comment by NghiaTranUIT** [comment]
@gkatsanos thanks for your suggestion. I've found the solution to Automatically capture all traffic that is called from the Terminal app.

It can work with NodeJS, cURL, Ruby, and Python without any manual config 💯 

For example: Just open Proxyman -> Click on "Terminal" -> New Terminal/iTerm shows up -> Run your NodeJS server here -> Traffic is automatically captured and send to Proxyman 👍 

I'm going to play around and support this feature now. It will resolve all pain we have 😄

**Comment by gkatsanos** [comment]
Sounds awesome! is it possible to start a terminal already now from the current Proxyman version or is this a future feature? :)

**Comment by NghiaTranUIT** [comment]
@gkatsanos here is a sneak peek of what I'm doing 😄 

- Proxyman automatically captures all traffic from this Terminal. Support cURL (no need `--proxy` flag), and NodeJS (including `fetch`, `axios`, `request`, and `superagent` libraries).

### Video Demo
- Setup: Use ExpressJS for a local web server
- Use `fetch` to call to an external API

=> ✅ Proxyman captures it automatically
=> ✅ User doesn't need to modify any source code.

https://user-images.githubusercontent.com/5878421/232966680-20327230-2818-49a2-b671-5b8f2b6c3f38.mp4

**Comment by NghiaTranUIT** [comment]
@gkatsanos just wondering: What's the NodeJS network library you're using? Currently, in the Beta build, It supports axios, got, superagent, fetch (node v18), node-fetch, and a built-in NodeJS `https` package.

It works out of the box ✅  (No Proxy config, no certificate)

**Comment by NghiaTranUIT** [comment]
Good news: @gkatsanos @sonic1981 @fishcharlie @dvcrn @shirshak55 @Cykelero

Proxyman can:
- Capture HTTP/HTTPS traffic from NodeJS (axios, fetch, node-fetch, got, superagent), Ruby, and Python `out of the box` ✅ 
- Don't need to set the Proxy or trust the certificate manually.
- 1-click and done 🎉 

## Download
Beta: https://download.proxyman.io/beta/Proxyman_4.6.1_Feature:_Automatic_Setup.dmg

## Automatic Setup
1. Proxyman -> Setup menu -> Automatic Setup -> Start the Terminal App
2. Grant AppleScript permission if needed
3. You can start your NodeJS server or run a script on this pre-configured Terminal
4. Done. Enjoy new traffic on Proxyman ✅ 

![CleanShot 2023-04-22 at 15 18 19@2x](https://user-images.githubusercontent.com/5878421/233774571-e57b14c0-321e-4c30-8df0-7592341a20ab.jpg)

## Manual Setup
- Just follow the instruction
![CleanShot 2023-04-22 at 15 23 20@2x](https://user-images.githubusercontent.com/5878421/233774565-4d03a1e0-c9b1-4c4f-8b37-88f45ee7d95b.jpg)

## Documentation:
https://docs.proxyman.io/automatic-setup/automatic-setup

## Demo video:
- Use Automatic Setup from Proxyman, to capture traffic from Python (`aiohttp` library). NodeJS is similar.
- Old approach: The user has to add the Proxy and disable the SSL Verification on their source code.
- New approach: 1-click and done ✅ 
- Video: https://drive.google.com/file/d/1UrWOJtY-tAFVv_OcgulTBB9qRlojgOnp/view?usp=sharing

**Comment by NghiaTranUIT** [comment]
@gkatsanos if you don't mind, please give it a try. I've tested with NodeJS (fetch). Proxyman can see traffic from `fetch` requests 👍

**Comment by Geczy** [comment]
trying this now, i think its working to capture requests, but it's not actually forwarding the request to the original server from what i can tell. im getting a HTTP/1.1 301 Moved Permanently on all outgoing requests from inside the electron app. i started the app from the terminal via `open ....xdyz/Title.app`

i don't have this issue in httptoolkit

**Comment by NghiaTranUIT** [comment]
@Geczy can you share with me how your setup your Electron app 🤔 

You have the source code, which allows you to start the Electron app from the Terminal, right?  Or you'd like to capture traffic from other Electron app?

**Comment by Geczy** [comment]
well previously in the production release, the electron app did not even display in proxyman as an "app" or any of the domains or anything. it's only captured if i use the terminal that proxyman opens to open the app.

i start this app by doing `open /System/Volumes/Data/Users/matt/Applications/xyz.app` in the spawned terminal

in this build, it does display. the electron app uses axios under the hood, if that matters. i don't have the source code for it.

**Comment by NghiaTranUIT** [comment]
I see, if you don't mind, can you share with me the name of your Electron app via nghia@proxyman.io ? I'd like to download production build, test it and fix it 👍

**Comment by Geczy** [comment]
sure, i sent you the email. thanks for taking a look. super sexy app

**Comment by NghiaTranUIT** [comment]
### New Beta build 🎉  
https://github.com/ProxymanApp/Proxyman/issues/1611#issuecomment-1521044841

**Comment by NghiaTranUIT** [comment]
Just a friendly reminder that we've released the automatic / manual setup 🎉 

cc @gkatsanos @sonic1981 @fishcharlie @dvcrn @shirshak55 @Cykelero

You can checkout the latest build or from this comment: https://github.com/ProxymanApp/Proxyman/issues/236#issuecomment-1518572201

**Comment by gkatsanos** [comment]
Thank you!

**Comment by NghiaTranUIT** [comment]
@Geczy I've fixed the ElectronJS issue, please get the Beta build from https://github.com/ProxymanApp/Proxyman/issues/1618#issuecomment-1528565327

**Comment by Geczy** [comment]
Can confirm it's fixed !

**Comment by ChiuMungZitAlexander** [comment]
My question is how can I disable it?

**Comment by NghiaTranUIT** [comment]
@ChiuMungZitAlexander Automatic Script doesn't start if you don't open the Terminal app. It only affects the current Terminal Session, not permanently change your OS. So, no need to disable it.

**Comment by gkatsanos** [comment]
Hey @NghiaTranUIT :
```

version 3.6.1
----------------------------------------------
------PROXYMAN AUTOMATIC SETUP SCRIPTS--------
----------------------------------------------
⭐️ Auto capture HTTP/HTTPS traffic from this Terminal app.
Support NodeJS: (axios, fetch, got, request, superagent)
Support Ruby: (http, net/http, net/https)
Support Python: (http, httplib, httplib2)

✅ Injected Proxyman variable environments to current shell

👉 Please start your local server or run your script from this Terminal.
set: +a: invalid variable name. See `help identifiers`

(Type 'help set' for related documentation)
 ✘  py[learning]  ~ 


```

I get this error when trying to open up a new 'automatic setup' terminal. I use
```
 fish -v
fish, version 3.6.1
```

**Comment by gkatsanos** [comment]
another issue I have (unrelated?) is even though I see one request, I dont see another one which happens to an external API endpoint but which passes through my VPN client.. could this be the reason?

**Comment by gkatsanos** [comment]
```
echo $PATH
/Users/gkatsanos/Library/pnpm /Users/gkatsanos/.pyenv/shims /opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims /Users/gkatsanos/.pyenv/bin /Users/gkatsanos/.nvm/versions/node/v16.19.0/bin /Users/gkatsanos/.rbenv/shims /Users/gkatsanos/.pyenv/bin /opt/homebrew/bin /usr/local/bin /Users/gkatsanos/.yarn/bin /usr/bin /bin /usr/sbin /sbin
```

**Comment by gkatsanos** [comment]
```
 ✘  py[learning]  ~  echo $PATH         
/Applications/Proxyman.app/Contents/Frameworks/ProxymanCore.framework/Versions/A/Resources/overrides/path /Users/gkatsanos/Library/pnpm /Users/gkatsanos/.pyenv/shims /opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims /Users/gkatsanos/.pyenv/bin /Users/gkatsanos/.nvm/versions/node/v16.19.0/bin /Users/gkatsanos/.rbenv/shims /Users/gkatsanos/.pyenv/bin /opt/homebrew/bin /usr/local/bin /Users/gkatsanos/.yarn/bin /usr/bin /bin /usr/sbin /sbin
 py[learning]  ~  


```

**Comment by leohxj** [comment]
add `export NODE_TLS_REJECT_UNAUTHORIZED=0` after  manual setup.

**Comment by NghiaTranUIT** [comment]
@leohxj a Beta build for you: https://download.proxyman.io/beta/Proxyman_4.11.0_Improve_UI_v1.dmg

**Comment by leohxj** [comment]
thanks @NghiaTranUIT , it works well

**Comment by shirshak55** [comment]
actually I don't recommend this. Last week , I think from Egypt government was hacked. Although, you may not be the target, I don't recommend messing with security.

I think proxy man should explicitly ask if they want to reduce this security?

**Comment by NghiaTranUIT** [comment]
@shirshak55 it doesn't globally modify your entire system. It only takes effect on the current Terminal app session when you need to debug your NodeJS project.

**Comment by leohxj** [comment]
yes, only for develop and use it locally

**Comment by tonyxiao** [comment]
Does this work with the built in node.js fetch now? Or is the `node-fetch` 3rd party lib required to use with proxyman?

**Comment by NghiaTranUIT** [comment]
It works for both. Native fetch and node-fetch

**Comment by tonyxiao** [comment]
Which env variable does native fetch use? When I look at the node docs it seems that fetch doesn't support proxy / agent agt all.

**Comment by NghiaTranUIT** [comment]
Auto Setup from Proxyman does more things than just the env. Proxyman uses global-agent to auto override the proxy of NodeJS Fetch in runtime.

You simply:
1. Open Proxyman, make sure you setup the certificate properly in Certificate menu -> Install for Mac.
2. Setup menu -> Auto -> start the Termnial.
3. Run your NodeJS script and this terminal and it's done ✅

**Comment by tonyxiao** [comment]
Hmm but the `global-agent` lib doesn't actually seem to support node 18 fetch. @see https://github.com/gajus/global-agent/issues/52 Does proxyman use the undici workaround too?

**Comment by NghiaTranUIT** [comment]
> Hmm but the `global-agent` lib doesn't actually seem to support node 18 fetch. @see [gajus/global-agent#52](https://github.com/gajus/global-agent/issues/52) Does proxyman use the undici workaround too?

Yes, it's.

**Comment by NghiaTranUIT** [comment]
FYI: We can capture all HTTPS Traffic from NodeJS with the Auto Setup (https://docs.proxyman.io/debug-devices/python)

No need to config the Proxy or manually trust the self-signed certificate on your Python code 👍
